# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Volunteer App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Volunteer App

pod ‘Firebase/Core’
pod 'Firebase/Database'
pod 'Firebase/Auth'

  target 'Volunteer AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Volunteer AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
